2024-07-22 02:47:15,344 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Configure stats pid to 635132
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/.config/wandb/settings
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/work/prudential_challange/wandb/settings
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_init.py:_log_setup():529] Logging user logs to /home/howt/work/prudential_challange/wandb/run-20240722_024715-kqewlln8/logs/debug.log
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_init.py:_log_setup():530] Logging internal logs to /home/howt/work/prudential_challange/wandb/run-20240722_024715-kqewlln8/logs/debug-internal.log
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_init.py:init():569] calling init triggers
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-22 02:47:15,345 INFO    MainThread:635132 [wandb_init.py:init():594] re-initializing run, found existing run on stack: 41bdjcp7
2024-07-22 02:47:15,347 INFO    MainThread:635132 [wandb_run.py:_finish():2107] finishing run howt51/ai-ethics-evaluation/41bdjcp7
2024-07-22 02:47:15,348 INFO    MainThread:635132 [jupyter.py:save_history():444] not saving jupyter history
2024-07-22 02:47:15,348 INFO    MainThread:635132 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-07-22 02:47:15,348 INFO    MainThread:635132 [wandb_init.py:_jupyter_teardown():457] cleaning up jupyter logic
2024-07-22 02:47:15,348 INFO    MainThread:635132 [wandb_run.py:_atexit_cleanup():2374] got exitcode: 0
2024-07-22 02:47:15,348 INFO    MainThread:635132 [wandb_run.py:_restore():2352] restore
2024-07-22 02:47:15,349 INFO    MainThread:635132 [wandb_run.py:_restore():2358] restore done
2024-07-22 02:47:19,667 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4016] rendering history
2024-07-22 02:47:19,668 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4048] rendering summary
2024-07-22 02:47:19,670 INFO    MainThread:635132 [wandb_run.py:_footer_sync_info():3975] logging synced files
2024-07-22 02:47:19,862 INFO    MainThread:635132 [wandb_init.py:init():619] starting backend
2024-07-22 02:47:19,862 INFO    MainThread:635132 [wandb_init.py:init():623] setting up manager
2024-07-22 02:47:19,863 INFO    MainThread:635132 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-22 02:47:19,864 INFO    MainThread:635132 [wandb_init.py:init():631] backend started and connected
2024-07-22 02:47:19,870 INFO    MainThread:635132 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-22 02:47:19,870 INFO    MainThread:635132 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-22 02:47:19,870 INFO    MainThread:635132 [wandb_init.py:init():720] updated telemetry
2024-07-22 02:47:19,872 INFO    MainThread:635132 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-22 02:47:21,323 INFO    MainThread:635132 [wandb_run.py:_on_init():2435] communicating current version
2024-07-22 02:47:21,432 INFO    MainThread:635132 [wandb_run.py:_on_init():2444] got version response 
2024-07-22 02:47:21,432 INFO    MainThread:635132 [wandb_init.py:init():804] starting run threads in backend
2024-07-22 02:47:36,572 INFO    MainThread:635132 [wandb_run.py:_console_start():2413] atexit reg
2024-07-22 02:47:36,573 INFO    MainThread:635132 [wandb_run.py:_redirect():2255] redirect: wrap_raw
2024-07-22 02:47:36,573 INFO    MainThread:635132 [wandb_run.py:_redirect():2320] Wrapping output streams.
2024-07-22 02:47:36,573 INFO    MainThread:635132 [wandb_run.py:_redirect():2345] Redirects installed.
2024-07-22 02:47:36,574 INFO    MainThread:635132 [wandb_init.py:init():847] run started, returning control to user process
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Configure stats pid to 635132
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/.config/wandb/settings
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/work/prudential_challange/wandb/settings
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_init.py:_log_setup():529] Logging user logs to /home/howt/work/prudential_challange/wandb/run-20240722_025353-r3jxhwo6/logs/debug.log
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_init.py:_log_setup():530] Logging internal logs to /home/howt/work/prudential_challange/wandb/run-20240722_025353-r3jxhwo6/logs/debug-internal.log
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_init.py:_jupyter_setup():475] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f3917ebd9a0>
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_init.py:init():569] calling init triggers
2024-07-22 02:53:53,536 INFO    MainThread:635132 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'objective': 'evaluate', 'num_class': 6, 'metric': 'multi_logloss'}
2024-07-22 02:53:53,537 INFO    MainThread:635132 [wandb_init.py:init():594] re-initializing run, found existing run on stack: kqewlln8
2024-07-22 02:53:53,538 INFO    MainThread:635132 [wandb_run.py:_finish():2107] finishing run howt51/ai-ethics-evaluation/kqewlln8
2024-07-22 02:53:53,539 INFO    MainThread:635132 [wandb_run.py:_atexit_cleanup():2374] got exitcode: 0
2024-07-22 02:53:53,539 INFO    MainThread:635132 [wandb_run.py:_restore():2352] restore
2024-07-22 02:53:53,539 INFO    MainThread:635132 [wandb_run.py:_restore():2358] restore done
2024-07-22 02:53:59,380 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4016] rendering history
2024-07-22 02:53:59,381 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4048] rendering summary
2024-07-22 02:53:59,386 INFO    MainThread:635132 [wandb_run.py:_footer_sync_info():3975] logging synced files
