2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Configure stats pid to 635132
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/.config/wandb/settings
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/work/prudential_challange/wandb/settings
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_init.py:_log_setup():529] Logging user logs to /home/howt/work/prudential_challange/wandb/run-20240722_024033-9igqx977/logs/debug.log
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_init.py:_log_setup():530] Logging internal logs to /home/howt/work/prudential_challange/wandb/run-20240722_024033-9igqx977/logs/debug-internal.log
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_init.py:_jupyter_setup():475] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f391e330560>
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_init.py:init():569] calling init triggers
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-22 02:40:33,024 INFO    MainThread:635132 [wandb_init.py:init():594] re-initializing run, found existing run on stack: hv9v3d76
2024-07-22 02:40:33,026 INFO    MainThread:635132 [wandb_run.py:_finish():2107] finishing run howt51/ai-ethics-evaluation/hv9v3d76
2024-07-22 02:40:33,027 INFO    MainThread:635132 [wandb_run.py:_atexit_cleanup():2374] got exitcode: 0
2024-07-22 02:40:33,027 INFO    MainThread:635132 [wandb_run.py:_restore():2352] restore
2024-07-22 02:40:33,027 INFO    MainThread:635132 [wandb_run.py:_restore():2358] restore done
2024-07-22 02:40:36,654 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4016] rendering history
2024-07-22 02:40:36,654 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4048] rendering summary
2024-07-22 02:40:36,658 INFO    MainThread:635132 [wandb_run.py:_footer_sync_info():3975] logging synced files
2024-07-22 02:40:36,751 INFO    MainThread:635132 [wandb_init.py:init():619] starting backend
2024-07-22 02:40:36,751 INFO    MainThread:635132 [wandb_init.py:init():623] setting up manager
2024-07-22 02:40:36,752 INFO    MainThread:635132 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-22 02:40:36,753 INFO    MainThread:635132 [wandb_init.py:init():631] backend started and connected
2024-07-22 02:40:36,759 INFO    MainThread:635132 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-22 02:40:36,759 INFO    MainThread:635132 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-22 02:40:36,759 INFO    MainThread:635132 [wandb_init.py:init():720] updated telemetry
2024-07-22 02:40:36,760 INFO    MainThread:635132 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-22 02:40:38,259 INFO    MainThread:635132 [wandb_run.py:_on_init():2435] communicating current version
2024-07-22 02:40:38,389 INFO    MainThread:635132 [wandb_run.py:_on_init():2444] got version response 
2024-07-22 02:40:38,390 INFO    MainThread:635132 [wandb_init.py:init():804] starting run threads in backend
2024-07-22 02:40:53,614 INFO    MainThread:635132 [wandb_run.py:_console_start():2413] atexit reg
2024-07-22 02:40:53,614 INFO    MainThread:635132 [wandb_run.py:_redirect():2255] redirect: wrap_raw
2024-07-22 02:40:53,614 INFO    MainThread:635132 [wandb_run.py:_redirect():2320] Wrapping output streams.
2024-07-22 02:40:53,615 INFO    MainThread:635132 [wandb_run.py:_redirect():2345] Redirects installed.
2024-07-22 02:40:53,615 INFO    MainThread:635132 [wandb_init.py:init():847] run started, returning control to user process
2024-07-22 02:40:53,668 INFO    MainThread:635132 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-07-22 02:40:53,668 INFO    MainThread:635132 [wandb_init.py:_pause_backend():440] pausing backend
2024-07-22 02:41:05,020 INFO    MainThread:635132 [wandb_init.py:_resume_backend():445] resuming backend
2024-07-22 02:41:05,034 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Configure stats pid to 635132
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/.config/wandb/settings
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from /home/howt/work/prudential_challange/wandb/settings
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_init.py:_log_setup():529] Logging user logs to /home/howt/work/prudential_challange/wandb/run-20240722_024105-8mhg0fqf/logs/debug.log
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_init.py:_log_setup():530] Logging internal logs to /home/howt/work/prudential_challange/wandb/run-20240722_024105-8mhg0fqf/logs/debug-internal.log
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_init.py:init():569] calling init triggers
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-22 02:41:05,035 INFO    MainThread:635132 [wandb_init.py:init():594] re-initializing run, found existing run on stack: 9igqx977
2024-07-22 02:41:05,036 INFO    MainThread:635132 [wandb_run.py:_finish():2107] finishing run howt51/ai-ethics-evaluation/9igqx977
2024-07-22 02:41:05,037 INFO    MainThread:635132 [jupyter.py:save_history():444] not saving jupyter history
2024-07-22 02:41:05,037 INFO    MainThread:635132 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-07-22 02:41:05,037 INFO    MainThread:635132 [wandb_init.py:_jupyter_teardown():457] cleaning up jupyter logic
2024-07-22 02:41:05,037 INFO    MainThread:635132 [wandb_run.py:_atexit_cleanup():2374] got exitcode: 0
2024-07-22 02:41:05,037 INFO    MainThread:635132 [wandb_run.py:_restore():2352] restore
2024-07-22 02:41:05,037 INFO    MainThread:635132 [wandb_run.py:_restore():2358] restore done
2024-07-22 02:41:09,038 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4016] rendering history
2024-07-22 02:41:09,038 INFO    MainThread:635132 [wandb_run.py:_footer_history_summary_info():4048] rendering summary
2024-07-22 02:41:09,041 INFO    MainThread:635132 [wandb_run.py:_footer_sync_info():3975] logging synced files
